"""initial

Revision ID: f53f72b5f5f1
Revises: 
Create Date: 2026-09-21 05:06:38.151937
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = 'f53f72b5f5f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tariff_name', sa.String(length=120), nullable=False),
    sa.Column('connection_type', sa.Enum('RESIDENTIAL', 'COMMERCIAL', 'INDUSTRIAL', name='connectiontype'), nullable=False),
    sa.Column('minimum_units', sa.Float(), nullable=False),
    sa.Column('maximum_units', sa.Float(), nullable=True),
    sa.Column('rate_per_unit', sa.Float(), nullable=False),
    sa.Column('fixed_charge', sa.Float(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tariffs_connection_type'), 'tariffs', ['connection_type'], unique=False)
    op.create_table('technicians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('employee_id', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('specialization', sa.String(length=120), nullable=False),
    sa.Column('availability_status', sa.Enum('AVAILABLE', 'BUSY', 'UNAVAILABLE', name='availabilitystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technicians_availability_status'), 'technicians', ['availability_status'], unique=False)
    op.create_index(op.f('ix_technicians_employee_id'), 'technicians', ['employee_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'BILLING_OFFICER', 'FIELD_TECHNICIAN', 'CUSTOMER_SERVICE_AGENT', 'CUSTOMER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity', sa.String(length=120), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('customer_number', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'CLOSED', name='customerstatus'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_customers_city'), 'customers', ['city'], unique=False)
    op.create_index(op.f('ix_customers_customer_number'), 'customers', ['customer_number'], unique=True)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('connection_number', sa.String(length=50), nullable=False),
    sa.Column('connection_type', sa.Enum('RESIDENTIAL', 'COMMERCIAL', 'INDUSTRIAL', name='connectiontype'), nullable=False),
    sa.Column('sanctioned_load', sa.Float(), nullable=False),
    sa.Column('tariff_type', sa.String(length=100), nullable=False),
    sa.Column('connection_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISCONNECTED', 'SUSPENDED', name='connectionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connections_connection_number'), 'connections', ['connection_number'], unique=True)
    op.create_index(op.f('ix_connections_customer_id'), 'connections', ['customer_id'], unique=False)
    op.create_table('bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('billing_month', sa.String(length=7), nullable=False),
    sa.Column('units_consumed', sa.Float(), nullable=False),
    sa.Column('energy_charge', sa.Float(), nullable=False),
    sa.Column('fixed_charge', sa.Float(), nullable=False),
    sa.Column('tax', sa.Float(), nullable=False),
    sa.Column('late_fee', sa.Float(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('bill_status', sa.Enum('GENERATED', 'PENDING', 'PAID', 'OVERDUE', 'CANCELLED', name='billstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'billing_month', name='uq_bill_connection_month')
    )
    op.create_index(op.f('ix_bills_bill_status'), 'bills', ['bill_status'], unique=False)
    op.create_index(op.f('ix_bills_billing_month'), 'bills', ['billing_month'], unique=False)
    op.create_index(op.f('ix_bills_connection_id'), 'bills', ['connection_id'], unique=False)
    op.create_table('complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('complaint_type', sa.Enum('POWER_FAILURE', 'VOLTAGE_ISSUE', 'METER_ISSUE', 'BILLING_ISSUE', 'CONNECTION_ISSUE', 'OTHER', name='complainttype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'EMERGENCY', name='priority'), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='complaintstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['technicians.id'], ),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_customer_id'), 'complaints', ['customer_id'], unique=False)
    op.create_index(op.f('ix_complaints_priority'), 'complaints', ['priority'], unique=False)
    op.create_index(op.f('ix_complaints_status'), 'complaints', ['status'], unique=False)
    op.create_table('meters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('meter_number', sa.String(length=80), nullable=False),
    sa.Column('meter_type', sa.String(length=80), nullable=False),
    sa.Column('installation_date', sa.Date(), nullable=False),
    sa.Column('initial_reading', sa.Float(), nullable=False),
    sa.Column('current_reading', sa.Float(), nullable=False),
    sa.Column('meter_status', sa.Enum('ACTIVE', 'FAULTY', 'REMOVED', name='meterstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meters_connection_id'), 'meters', ['connection_id'], unique=False)
    op.create_index(op.f('ix_meters_meter_number'), 'meters', ['meter_number'], unique=True)
    op.create_table('service_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('request_type', sa.Enum('NEW_CONNECTION', 'LOAD_CHANGE', 'METER_REPLACEMENT', 'NAME_CHANGE', 'ADDRESS_CHANGE', 'DISCONNECTION', 'RECONNECTION', name='servicerequesttype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requested_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'COMPLETED', name='servicerequeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_requests_customer_id'), 'service_requests', ['customer_id'], unique=False)
    op.create_table('complaint_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_history_complaint_id'), 'complaint_history', ['complaint_id'], unique=False)
    op.create_table('meter_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meter_id', sa.Integer(), nullable=False),
    sa.Column('reading_date', sa.Date(), nullable=False),
    sa.Column('previous_reading', sa.Float(), nullable=False),
    sa.Column('current_reading', sa.Float(), nullable=False),
    sa.Column('units_consumed', sa.Float(), nullable=False),
    sa.Column('reading_source', sa.Enum('MANUAL', 'SMART_METER', 'FIELD_TECHNICIAN', name='readingsource'), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meter_id', 'reading_date', name='uq_meter_reading_date')
    )
    op.create_index('ix_meter_readings_meter_date', 'meter_readings', ['meter_id', 'reading_date'], unique=False)
    op.create_index(op.f('ix_meter_readings_meter_id'), 'meter_readings', ['meter_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.Enum('UPI', 'CARD', 'NET_BANKING', 'WALLET', name='paymentmethod'), nullable=False),
    sa.Column('transaction_id', sa.String(length=120), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_bill_id'), 'payments', ['bill_id'], unique=False)
    op.create_index(op.f('ix_payments_transaction_id'), 'payments', ['transaction_id'], unique=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_bill_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_meter_readings_meter_id'), table_name='meter_readings')
    op.drop_index('ix_meter_readings_meter_date', table_name='meter_readings')
    op.drop_table('meter_readings')
    op.drop_index(op.f('ix_complaint_history_complaint_id'), table_name='complaint_history')
    op.drop_table('complaint_history')
    op.drop_index(op.f('ix_service_requests_customer_id'), table_name='service_requests')
    op.drop_table('service_requests')
    op.drop_index(op.f('ix_meters_meter_number'), table_name='meters')
    op.drop_index(op.f('ix_meters_connection_id'), table_name='meters')
    op.drop_table('meters')
    op.drop_index(op.f('ix_complaints_status'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_priority'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_customer_id'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_bills_connection_id'), table_name='bills')
    op.drop_index(op.f('ix_bills_billing_month'), table_name='bills')
    op.drop_index(op.f('ix_bills_bill_status'), table_name='bills')
    op.drop_table('bills')
    op.drop_index(op.f('ix_connections_customer_id'), table_name='connections')
    op.drop_index(op.f('ix_connections_connection_number'), table_name='connections')
    op.drop_table('connections')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_number'), table_name='customers')
    op.drop_index(op.f('ix_customers_city'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_technicians_employee_id'), table_name='technicians')
    op.drop_index(op.f('ix_technicians_availability_status'), table_name='technicians')
    op.drop_table('technicians')
    op.drop_index(op.f('ix_tariffs_connection_type'), table_name='tariffs')
    op.drop_table('tariffs')
    # ### end Alembic commands ###
